# Site settings
title: UKHB Randomizer
email: cld251@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Song randomizer for BHS Harmony Brigades
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://randomukhb.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
